-- Expand the versioned Story Arc catalog with 20 commercially useful structures.
-- IDs mirror StoryArcTemplate.swift so locally-created arcs remain FK-valid.

insert into public.story_arc_templates (id, name, description, beats) values
  (
    'a0000001-0000-0000-0000-000000000008',
    'Romance / HEA',
    'A relationship-first arc built around attraction, resistance, vulnerability, rupture, and an earned happily-ever-after or happy-for-now ending.',
    $$[{"role":"ordinary_life","label":"Ordinary Life","description":"Establish each lead's life, unmet need, and emotional defenses before the relationship changes them."},{"role":"meet_attraction","label":"Meet / Attraction","description":"Bring the leads together and create a meaningful spark, friction, or pull between them."},{"role":"resistance","label":"Resistance","description":"Give the leads credible internal or external reasons not to pursue the relationship."},{"role":"connection_deepens","label":"Connection Deepens","description":"Build trust, chemistry, shared experience, and vulnerability through consequential interaction."},{"role":"midpoint_intimacy","label":"Midpoint Intimacy","description":"Cross an emotional or physical threshold that makes the relationship harder to dismiss."},{"role":"pressure_test","label":"Pressure Test","description":"Apply outside stakes and personal flaws that strain the growing bond."},{"role":"rupture","label":"Rupture","description":"Break the relationship or its apparent future through a choice, revelation, fear, or betrayal."},{"role":"realization","label":"Realization","description":"Force the central emotional truth into view and make avoidance impossible."},{"role":"grand_choice","label":"Grand Choice","description":"Make a costly, active choice that proves what the relationship now means."},{"role":"hea_hfn","label":"HEA / HFN","description":"Resolve the core romantic conflict with an earned committed future together."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000009',
    'Psychological / Domestic Thriller',
    'A suspense arc in which ordinary life destabilizes through suspicion, manipulation, layered revelations, betrayal, and a final confrontation with the deeper truth.',
    $$[{"role":"normal_surface","label":"Normal Surface","description":"Establish a believable domestic or psychological status quo with subtle fault lines underneath."},{"role":"destabilizing_incident","label":"Destabilizing Incident","description":"Introduce the event, discovery, or behavior that makes the protagonist question what is real or safe."},{"role":"suspicion_grows","label":"Suspicion Grows","description":"Accumulate contradictions, evasions, and threatening details without resolving them too early."},{"role":"first_reveal","label":"First Reveal","description":"Confirm that an important assumption was wrong and reframe the danger."},{"role":"isolation","label":"Isolation","description":"Reduce the protagonist's reliable support, credibility, options, or sense of control."},{"role":"midpoint_truth_shift","label":"Midpoint Truth Shift","description":"Reveal a larger truth that changes who appears dangerous and what is at stake."},{"role":"apparent_answer","label":"Apparent Answer","description":"Offer a convincing explanation or temporary solution that seems to settle the central suspicion."},{"role":"deeper_betrayal","label":"Deeper Betrayal","description":"Expose the hidden betrayal, manipulation, or threat beneath the apparent answer."},{"role":"final_confrontation","label":"Final Confrontation","description":"Force the protagonist to confront the true source of danger and act on the full truth."},{"role":"aftermath","label":"Aftermath","description":"Resolve the immediate threat and show the psychological or relational cost of what was uncovered."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000010',
    'Romantasy',
    'A dual-engine fantasy arc in which the external quest and central romance escalate together and become inseparable at the climax.',
    $$[{"role":"ordinary_world","label":"Ordinary World","description":"Establish the protagonist, the fantasy world, and the emotional conditions before disruption."},{"role":"magical_disruption","label":"Magical Disruption","description":"Introduce the threat, power, mission, or revelation that overturns the status quo."},{"role":"dangerous_attraction","label":"Dangerous Attraction","description":"Create a compelling romantic pull complicated by allegiance, danger, status, or mistrust."},{"role":"binding_choice","label":"Binding Choice","description":"Force a commitment that ties the protagonist to both the external conflict and romantic counterpart."},{"role":"quest_and_bond","label":"Quest and Bond","description":"Escalate trials while trust, desire, and mutual dependence deepen."},{"role":"midpoint_revelation","label":"Midpoint Revelation","description":"Reveal a truth about the world, mission, power, or relationship that changes the trajectory."},{"role":"divided_loyalties","label":"Divided Loyalties","description":"Make romantic desire and external duty meaningfully conflict."},{"role":"catastrophic_break","label":"Catastrophic Break","description":"Shatter the current plan or relationship and expose the cost of choosing wrongly."},{"role":"united_choice","label":"United Choice","description":"Have the leads choose what they will stand for together despite the cost."},{"role":"final_battle_and_choice","label":"Final Battle and Choice","description":"Resolve the primary external conflict through a climax inseparable from the central emotional choice."},{"role":"new_order_together","label":"New Order Together","description":"Establish the changed world and the earned state of the relationship."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000011',
    'Suspense / Countdown Thriller',
    'A pressure-driven thriller structure organized around a credible threat, shrinking time, narrowing options, reversals, and a deadline climax.',
    $$[{"role":"threat_appears","label":"Threat Appears","description":"Introduce a concrete danger with consequences the protagonist cannot ignore."},{"role":"clock_starts","label":"Clock Starts","description":"Create a meaningful deadline and force the protagonist into action."},{"role":"first_pursuit","label":"First Pursuit","description":"Escalate pursuit, investigation, or evasion while proving the threat is active."},{"role":"narrowing_options","label":"Narrowing Options","description":"Close off easy solutions and make delay increasingly costly."},{"role":"midpoint_reversal","label":"Midpoint Reversal","description":"Change the protagonist's understanding of the threat, target, or enemy."},{"role":"major_loss","label":"Major Loss","description":"Inflict a serious failure or loss that makes the deadline feel nearly impossible."},{"role":"final_lead","label":"Final Lead","description":"Reveal the actionable path that makes one last attempt possible."},{"role":"race_to_deadline","label":"Race to the Deadline","description":"Compress time and escalate obstacles as the protagonist commits everything to the final attempt."},{"role":"showdown","label":"Showdown","description":"Resolve the central threat at or immediately before the deadline."},{"role":"aftermath","label":"Aftermath","description":"Show the immediate consequences and the new state after the threat is resolved."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000012',
    'Science-Fiction Problem / Survival',
    'A science-fiction problem-solving arc built around an impossible condition, iterative failure, discovery, sacrifice, and a hard-earned solution.',
    $$[{"role":"baseline_world","label":"Baseline World","description":"Establish the system, environment, technology, and ordinary operating assumptions."},{"role":"impossible_problem","label":"Impossible Problem","description":"Introduce the anomaly, disaster, discovery, or survival problem that breaks those assumptions."},{"role":"first_hypothesis","label":"First Hypothesis","description":"Commit to an initial explanation or solution based on the best available evidence."},{"role":"failed_solution","label":"Failed Solution","description":"Demonstrate that the first approach is insufficient and make the problem more dangerous or complex."},{"role":"deeper_discovery","label":"Deeper Discovery","description":"Reveal the hidden rule, mechanism, or truth that changes the problem definition."},{"role":"resource_collapse","label":"Resource Collapse","description":"Remove critical time, energy, safety, personnel, or technological capacity."},{"role":"breakthrough","label":"Breakthrough","description":"Achieve the conceptual or technical insight that makes a real solution possible."},{"role":"sacrifice_choice","label":"Sacrifice Choice","description":"Force a costly decision about what must be risked or surrendered for the solution to work."},{"role":"final_solution","label":"Final Solution","description":"Execute the decisive solution under maximum pressure."},{"role":"changed_world","label":"Changed World","description":"Resolve survival and show how the discovery permanently changes the characters or world."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000013',
    'Dystopian Rebellion',
    'An oppression-to-resistance arc in which the protagonist awakens to systemic control, commits to defiance, pays for resistance, and confronts the regime.',
    $$[{"role":"controlled_normal","label":"Controlled Normal","description":"Establish the rules, rewards, punishments, and normalized compromises of the oppressive system."},{"role":"crack_in_system","label":"Crack in the System","description":"Expose a contradiction, injustice, or forbidden truth that the protagonist cannot unsee."},{"role":"awakening","label":"Awakening","description":"Turn private doubt into a clearer understanding of the system and the protagonist's place in it."},{"role":"first_defiance","label":"First Defiance","description":"Make an irreversible act of resistance that creates real consequences."},{"role":"resistance_builds","label":"Resistance Builds","description":"Expand allies, tactics, and stakes while the regime becomes more aware of the threat."},{"role":"regime_retaliates","label":"Regime Retaliates","description":"Demonstrate the system's power through punishment, repression, or targeted loss."},{"role":"betrayal_or_loss","label":"Betrayal / Loss","description":"Break trust or remove a key source of hope, forcing a reassessment of the rebellion."},{"role":"uprising_choice","label":"Uprising Choice","description":"Commit to the decisive action despite the personal and collective cost."},{"role":"confrontation","label":"Confrontation","description":"Bring the rebellion and regime into decisive conflict."},{"role":"new_order_cost","label":"New Order / Cost","description":"Show what changed, what did not, and what the victory or failure ultimately cost."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000014',
    'Dark Romance',
    'A high-intensity romance arc centered on dangerous attraction, power imbalance, boundaries, vulnerability, rupture, reckoning, and an earned chosen relationship.',
    $$[{"role":"dangerous_encounter","label":"Dangerous Encounter","description":"Introduce an attraction carrying credible emotional, social, moral, or physical risk."},{"role":"boundary_drawn","label":"Boundary Drawn","description":"Establish the limits, fears, and power conditions that define the relationship's danger."},{"role":"entanglement","label":"Entanglement","description":"Make separation harder as desire, leverage, dependency, or shared stakes increase."},{"role":"power_shift","label":"Power Shift","description":"Change who holds leverage or what each character believes about the other."},{"role":"vulnerability_revealed","label":"Vulnerability Revealed","description":"Expose a truth or wound that complicates the apparent power dynamic."},{"role":"moral_pressure","label":"Moral Pressure","description":"Force the relationship against a meaningful ethical, emotional, or external limit."},{"role":"betrayal_or_rupture","label":"Betrayal / Rupture","description":"Break trust or make continuation of the relationship appear unacceptable or impossible."},{"role":"reckoning","label":"Reckoning","description":"Force accountability, self-recognition, and confrontation with the relationship's central harm or fear."},{"role":"chosen_terms","label":"Chosen Terms","description":"Make a decisive choice that establishes what the relationship can and cannot become."},{"role":"earned_resolution","label":"Earned Resolution","description":"Resolve the central romantic conflict with agency, consequences, and a stable chosen future."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000015',
    'Epic Fantasy Quest',
    'A large-scale quest arc built around a threatened world, fellowship, widening trials, revelation, catastrophic setback, sacrifice, and a final objective.',
    $$[{"role":"threatened_home","label":"Threatened Home","description":"Establish the world and the danger that makes remaining unchanged impossible."},{"role":"call_or_mission","label":"Call / Mission","description":"Define the quest, objective, or burden that must be undertaken."},{"role":"fellowship_forms","label":"Fellowship Forms","description":"Assemble the companions, alliances, or obligations needed for the journey."},{"role":"first_threshold","label":"First Threshold","description":"Leave safety behind and enter the true arena of the quest."},{"role":"trials_and_world","label":"Trials and Wider World","description":"Escalate obstacles while revealing the scale, cultures, powers, and costs of the conflict."},{"role":"midpoint_revelation","label":"Midpoint Revelation","description":"Reveal a truth about the enemy, artifact, prophecy, mission, or protagonist that changes the quest."},{"role":"catastrophic_setback","label":"Catastrophic Setback","description":"Break the plan, fellowship, or hope through a major defeat or loss."},{"role":"regroup_and_sacrifice","label":"Regroup and Sacrifice","description":"Recommit through a costly choice informed by what the journey has taught."},{"role":"final_objective","label":"Final Objective","description":"Confront the primary antagonist or complete the decisive objective."},{"role":"return_or_new_age","label":"Return / New Age","description":"Show the transformed world, surviving relationships, and consequences of the quest."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000016',
    'Seven-Point Story Structure',
    'A compact seven-point plotting framework: hook, first turn, first pinch, midpoint, second pinch, second turn, and climactic resolution.',
    $$[{"role":"hook","label":"Hook","description":"Establish the protagonist, central lack, and starting conditions in direct contrast with the eventual ending."},{"role":"plot_turn_one","label":"Plot Turn One","description":"Introduce the event that commits the protagonist to the central story problem."},{"role":"pinch_point_one","label":"Pinch Point One","description":"Apply direct pressure from the antagonistic force and demonstrate the cost of failure."},{"role":"midpoint","label":"Midpoint","description":"Shift the protagonist from reaction toward active pursuit through a major realization or reversal."},{"role":"pinch_point_two","label":"Pinch Point Two","description":"Deliver the strongest pressure or loss before the endgame and strip away an important support."},{"role":"plot_turn_two","label":"Plot Turn Two","description":"Reveal or earn the final information, capacity, or decision needed to face the ending."},{"role":"resolution","label":"Resolution","description":"Deliver the decisive confrontation and resolve the central story problem."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000017',
    'Horror / Escalating Dread',
    'A horror arc that moves from subtle wrongness through intrusion, confirmation, isolation, rule discovery, full manifestation, and a survival-or-doom climax.',
    $$[{"role":"normal_with_crack","label":"Normal with a Crack","description":"Establish ordinary life while planting a specific detail that feels wrong before its meaning is known."},{"role":"first_intrusion","label":"First Intrusion","description":"Let the threat cross into the protagonist's world in a way that can no longer be fully ignored."},{"role":"denial_or_misread","label":"Denial / Misread","description":"Allow a plausible explanation or wrong interpretation to delay full understanding."},{"role":"confirmation","label":"Confirmation","description":"Prove that the threat is real and more dangerous than initially believed."},{"role":"isolation","label":"Isolation","description":"Cut off safety, help, escape, credibility, or familiar rules."},{"role":"rules_discovered","label":"Rules Discovered","description":"Reveal enough about the threat's nature or pattern to make resistance possible but costly."},{"role":"false_safety","label":"False Safety","description":"Offer a temporary escape or solution that fails to end the threat."},{"role":"full_manifestation","label":"Full Manifestation","description":"Bring the horror into its most complete and unavoidable form."},{"role":"survival_confrontation","label":"Survival Confrontation","description":"Force the protagonist into the decisive encounter with the threat."},{"role":"final_image","label":"Final Image","description":"Resolve survival or doom while leaving the intended emotional residue of the horror."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000018',
    'Sports Romance',
    'A romance structure that interlocks a competitive season or athletic goal with attraction, forced proximity, public pressure, setbacks, and an emotional payoff.',
    $$[{"role":"season_setup","label":"Season Setup","description":"Establish the athletic stakes, team or competitive environment, and each lead's current priorities."},{"role":"meet_or_rivalry","label":"Meet / Rivalry","description":"Create the relationship spark through competition, collision, recruitment, or a shared sports context."},{"role":"forced_proximity","label":"Forced Proximity","description":"Give the leads a credible reason to spend meaningful time together despite resistance."},{"role":"chemistry_builds","label":"Chemistry Builds","description":"Deepen attraction and trust while training, competition, or team pressures escalate."},{"role":"first_commitment","label":"First Commitment","description":"Cross a relationship threshold that makes the connection real and consequential."},{"role":"public_private_pressure","label":"Public / Private Pressure","description":"Bring career, team, reputation, family, or media pressures against the relationship."},{"role":"athletic_setback","label":"Athletic Setback","description":"Create a meaningful competitive loss, injury, failure, or career threat that changes priorities."},{"role":"relationship_rupture","label":"Relationship Rupture","description":"Break the couple's apparent future at the moment both sport and relationship stakes peak."},{"role":"game_day_choice","label":"Game-Day Choice","description":"Resolve the defining athletic challenge alongside the central emotional choice."},{"role":"hea_hfn","label":"HEA / HFN","description":"Deliver the earned relationship future and show how it fits with the characters' athletic lives."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000019',
    'Romantic Suspense',
    'A paired romance-and-danger arc in which trust grows under threat and the relationship becomes essential to surviving the final confrontation.',
    $$[{"role":"danger_hook","label":"Danger Hook","description":"Introduce the threat that forces the leads into the same problem."},{"role":"forced_alliance","label":"Forced Alliance","description":"Make cooperation necessary even though trust is incomplete."},{"role":"distrust","label":"Distrust","description":"Expose reasons the leads cannot yet fully rely on one another."},{"role":"intimacy_under_pressure","label":"Intimacy Under Pressure","description":"Deepen attraction and vulnerability while danger keeps increasing."},{"role":"threat_escalates","label":"Threat Escalates","description":"Make the antagonist or danger more immediate, capable, and personal."},{"role":"midpoint_reveal","label":"Midpoint Reveal","description":"Reveal a truth that changes both the investigation and the relationship."},{"role":"betrayal_or_misread","label":"Betrayal / Misread","description":"Break trust or make one lead appear complicit with the threat."},{"role":"trust_choice","label":"Trust Choice","description":"Make an active, risky decision to trust based on earned knowledge rather than convenience."},{"role":"joint_showdown","label":"Joint Showdown","description":"Resolve the central danger through coordinated action and emotional commitment."},{"role":"safety_and_commitment","label":"Safety and Commitment","description":"Resolve the threat and establish the earned romantic future."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000020',
    'Conspiracy / Artifact Thriller',
    'A discovery-and-pursuit thriller built around clues, expanding conspiracy, hidden history, betrayal, decoding, and a race to prevent a larger outcome.',
    $$[{"role":"discovery","label":"Discovery","description":"Uncover the object, document, secret, or anomaly that opens the larger mystery."},{"role":"pursuit_begins","label":"Pursuit Begins","description":"Make possession of the discovery dangerous and force the protagonist to act."},{"role":"first_clue","label":"First Clue","description":"Resolve the first layer while pointing toward a larger hidden system."},{"role":"conspiracy_expands","label":"Conspiracy Expands","description":"Reveal that the opposition is broader, older, or more powerful than expected."},{"role":"ally_or_betrayal","label":"Ally / Betrayal","description":"Complicate the pursuit by changing who can be trusted."},{"role":"hidden_history_reveal","label":"Hidden History Reveal","description":"Expose the deeper origin or meaning of the artifact, conspiracy, or secret."},{"role":"apparent_defeat","label":"Apparent Defeat","description":"Put the antagonist in control and remove the protagonist's obvious path forward."},{"role":"final_decoding","label":"Final Decoding","description":"Complete the insight that reveals what must happen next and why."},{"role":"race_to_prevent","label":"Race to Prevent","description":"Escalate toward the irreversible consequence the conspiracy is trying to cause."},{"role":"confrontation_and_truth","label":"Confrontation and Truth","description":"Defeat or expose the central threat while making the hidden truth unavoidable."},{"role":"aftermath","label":"Aftermath","description":"Resolve the immediate conspiracy and show what the revealed truth changes."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000021',
    'Progression Fantasy / LitRPG',
    'A growth-driven fantasy arc organized around discovering a system, incremental advancement, escalating tests, defeat, breakthrough, and a tier-defining climax.',
    $$[{"role":"weak_start","label":"Weak Start","description":"Establish the protagonist's limitations, status, and the hierarchy they cannot yet overcome."},{"role":"system_discovered","label":"System Discovered","description":"Reveal the rules, power system, progression path, or game-like structure that makes advancement possible."},{"role":"first_gain","label":"First Gain","description":"Earn the first meaningful improvement and commit to progression."},{"role":"training_and_trials","label":"Training and Trials","description":"Build competence through increasingly costly practice, quests, tests, or fights."},{"role":"first_boss","label":"First Major Test","description":"Measure progress against an opponent or challenge that exposes remaining weaknesses."},{"role":"new_tier","label":"New Tier","description":"Achieve a breakthrough that changes the protagonist's options and status."},{"role":"stronger_rival","label":"Stronger Rival","description":"Introduce an opponent, faction, or challenge that makes the new level insufficient."},{"role":"major_defeat","label":"Major Defeat","description":"Inflict a loss that exposes a fundamental weakness in the current path."},{"role":"breakthrough","label":"Breakthrough","description":"Earn a new understanding, technique, alliance, or evolution through the consequences of defeat."},{"role":"tier_climax","label":"Tier Climax","description":"Win or survive the defining challenge of this progression stage."},{"role":"next_horizon","label":"Next Horizon","description":"Resolve the current progression arc while revealing the larger level still ahead."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000022',
    'Historical War / Survival',
    'A historical survival arc in which ordinary life is ruptured by conflict, adaptation becomes necessary, losses accumulate, and survival requires an impossible choice.',
    $$[{"role":"life_before","label":"Life Before","description":"Establish the social world, relationships, duties, and historical conditions before open rupture."},{"role":"war_arrives","label":"War Arrives","description":"Bring the historical conflict directly into the protagonist's life."},{"role":"adaptation","label":"Adaptation","description":"Force new roles, routines, allegiances, or survival strategies."},{"role":"first_loss","label":"First Loss","description":"Make the cost of the conflict personal and irreversible."},{"role":"deepening_conflict","label":"Deepening Conflict","description":"Escalate scarcity, danger, displacement, duty, or divided loyalties."},{"role":"impossible_choice","label":"Impossible Choice","description":"Force a decision in which every available option carries serious moral or personal cost."},{"role":"major_loss_or_betrayal","label":"Major Loss / Betrayal","description":"Destroy a major source of safety, trust, or hope."},{"role":"final_endurance","label":"Final Endurance","description":"Commit to the final course of action under the harshest conditions."},{"role":"decisive_event","label":"Decisive Event","description":"Bring the protagonist through the defining confrontation, escape, battle, or survival test."},{"role":"aftermath_and_memory","label":"Aftermath and Memory","description":"Show survival, grief, change, and what the historical experience leaves behind."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000023',
    'Coming-of-Age / Bildungsroman',
    'An identity-development arc built around disruption, experimentation, belonging, consequences, disillusionment, self-recognition, and an adult choice.',
    $$[{"role":"sheltered_identity","label":"Sheltered Identity","description":"Establish the protagonist's inherited identity, assumptions, and limited understanding of the world."},{"role":"first_disruption","label":"First Disruption","description":"Introduce an experience that makes the old identity insufficient."},{"role":"experimentation","label":"Experimentation","description":"Let the protagonist test new roles, freedoms, relationships, or beliefs."},{"role":"belonging_and_conflict","label":"Belonging and Conflict","description":"Offer meaningful belonging while exposing the compromises it demands."},{"role":"first_consequence","label":"First Consequence","description":"Make a choice produce an irreversible emotional, social, or practical cost."},{"role":"disillusionment","label":"Disillusionment","description":"Break an important idealization of a person, institution, relationship, or self-image."},{"role":"self_recognition","label":"Self-Recognition","description":"Bring the protagonist to a clearer understanding of who they are and what they value."},{"role":"adult_choice","label":"Adult Choice","description":"Make a consequential decision based on the emerging self rather than inherited expectations."},{"role":"leaving_or_returning","label":"Leaving / Returning","description":"Show the immediate consequence of the adult choice in relation to the old world."},{"role":"integrated_identity","label":"Integrated Identity","description":"Resolve the arc with a more mature, self-authored identity."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000024',
    'Revenge',
    'A vengeance arc built around injury, vow, preparation, escalating retaliation, moral cost, counterattack, reckoning, and the consequences of revenge.',
    $$[{"role":"injury","label":"Injury","description":"Inflict the wrong, loss, humiliation, or betrayal that creates the desire for revenge."},{"role":"vow","label":"Vow","description":"Turn pain into a concrete commitment to retaliate."},{"role":"preparation","label":"Preparation","description":"Acquire knowledge, access, allies, skills, or leverage needed to act."},{"role":"first_retribution","label":"First Retribution","description":"Deliver an early success that proves revenge is possible and raises the stakes."},{"role":"cost_revealed","label":"Cost Revealed","description":"Show collateral damage or personal corruption caused by the pursuit."},{"role":"counterstrike","label":"Counterstrike","description":"Let the target or system retaliate effectively and put the avenger in danger."},{"role":"moral_crossroads","label":"Moral Crossroads","description":"Force recognition of what revenge is demanding and whether the original goal still justifies it."},{"role":"final_hunt","label":"Final Hunt","description":"Commit to the last pursuit with no illusion about its cost."},{"role":"reckoning","label":"Reckoning","description":"Bring avenger and target into the decisive confrontation."},{"role":"consequence","label":"Consequence","description":"Resolve what revenge achieved, destroyed, or failed to repair."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000025',
    'Heist / Caper',
    'A plan-execution arc built around a desirable target, specialized crew, preparation, layered complications, betrayal, improvisation, and escape or capture.',
    $$[{"role":"target","label":"The Target","description":"Establish the prize, obstacle, and why taking it matters."},{"role":"motive","label":"The Motive","description":"Create the pressure or opportunity that makes the heist worth attempting."},{"role":"crew_assembled","label":"Crew Assembled","description":"Recruit the specialized people and define the tensions inside the team."},{"role":"plan_and_prep","label":"Plan and Prep","description":"Build the operation, gather tools and intelligence, and expose likely failure points."},{"role":"first_complication","label":"First Complication","description":"Introduce a change that invalidates part of the plan before or during execution."},{"role":"execution_begins","label":"Execution Begins","description":"Cross the point of no return and put the plan into motion."},{"role":"plan_breaks","label":"The Plan Breaks","description":"Destroy the expected path to success and force live improvisation."},{"role":"betrayal_or_twist","label":"Betrayal / Twist","description":"Reveal hidden motives, double-crosses, or a truth about the target that changes the job."},{"role":"improvisation","label":"Improvisation","description":"Use the crew's earned skills and relationships to create a new route through the failure."},{"role":"escape_or_capture","label":"Escape / Capture","description":"Resolve possession of the target and the team's immediate survival or capture."},{"role":"division_and_aftermath","label":"Division and Aftermath","description":"Settle the prize, loyalties, consequences, and what remains of the crew."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000026',
    'Redemption / Rebirth',
    'A moral transformation arc in which a damaged or compromised protagonist receives a chance to change, relapses, faces the truth, sacrifices, and acts differently when it matters.',
    $$[{"role":"broken_state","label":"Broken State","description":"Establish the protagonist's damaged pattern, moral failure, or self-defeating way of living."},{"role":"chance_to_change","label":"Chance to Change","description":"Introduce the person, event, responsibility, or consequence that makes another path possible."},{"role":"refusal_or_old_pattern","label":"Refusal / Old Pattern","description":"Show the protagonist retreating into the familiar behavior that created the problem."},{"role":"first_good_choice","label":"First Good Choice","description":"Make a meaningful but incomplete choice toward change."},{"role":"progress","label":"Progress","description":"Build evidence of change through repeated costly choices rather than declarations."},{"role":"relapse","label":"Relapse","description":"Return the protagonist to the old pattern at serious cost."},{"role":"truth_faced","label":"Truth Faced","description":"Force full recognition of the harm, lie, or fear beneath the old identity."},{"role":"sacrifice","label":"Sacrifice","description":"Give up something genuinely valued in order to act according to the new truth."},{"role":"redemptive_act","label":"Redemptive Act","description":"Prove the transformation through decisive action under maximum pressure."},{"role":"changed_life","label":"Changed Life","description":"Resolve with the consequences of the redemptive choice and a demonstrably different way of living."}]$$::jsonb
  ),
  (
    'a0000001-0000-0000-0000-000000000027',
    'Family Saga / Generational',
    'A multigenerational family arc built around founding choices, inheritance, buried conflict, generational repetition, fracture, revelation, reckoning, and legacy.',
    $$[{"role":"founding_choice","label":"Founding Choice","description":"Establish the consequential decision, relationship, wound, or ambition that shapes the family system."},{"role":"first_inheritance","label":"First Inheritance","description":"Show how the founding generation's choices become conditions imposed on the next."},{"role":"family_expands","label":"Family Expands","description":"Develop alliances, marriages, rivalries, resources, and competing visions across the family."},{"role":"buried_conflict","label":"Buried Conflict","description":"Deepen the secret, resentment, debt, or unresolved wrong carried across time."},{"role":"generational_turn","label":"Generational Turn","description":"Shift power or perspective to a new generation that interprets the inheritance differently."},{"role":"fracture","label":"Fracture","description":"Break the family system through a death, betrayal, succession fight, revelation, or separation."},{"role":"inherited_truth_revealed","label":"Inherited Truth Revealed","description":"Expose the hidden history that explains the repeating conflict."},{"role":"reckoning_across_generations","label":"Reckoning Across Generations","description":"Force living generations to confront the inherited pattern and one another."},{"role":"reconciliation_or_repeat","label":"Reconciliation / Repeat","description":"Show whether the family transforms the pattern or consciously repeats it."},{"role":"legacy","label":"Legacy","description":"Resolve the saga by showing what is ultimately passed forward."}]$$::jsonb
  )
on conflict (id) do update set
  name        = excluded.name,
  description = excluded.description,
  beats       = excluded.beats,
  updated_at  = now();
