-- ============================================================================
-- Add generation_output_id to section_embeddings (lineage from section
-- memory to the generation output that produced it).
--
-- Bug: section_embeddings is keyed by outline_section_id with no lineage back
-- to the generation_output that produced the structured memory. Deleting a
-- generation_output left its source section_embeddings row in place, which
-- then contaminated future Project State queries with the deleted run's
-- content (kevbot-brain chunk for the 12:00 EDT fix).
--
-- Fix:
--   1. Add generation_output_id UUID (nullable for back-compat with pre-fix
--      rows that have no lineage).
--   2. Index it for the Delete Everywhere cascade check.
--   3. Add a trigger on generation_outputs AFTER DELETE that removes the
--      matching section_embeddings row. The trigger ONLY removes the row if
--      it was generated by the deleted output — if a newer output has since
--      overwritten the section_embeddings row (newer generation_output_id),
--      the WHERE clause won't match and the row is preserved.
--   4. One-time cleanup of pre-existing dirty rows where the source output
--      has been deleted but the memory is still there. We do this by:
--      a) Backfilling generation_output_id for rows where a matching output
--         still exists (join on outline_section_id, most recent).
--      b) Deleting rows where no matching output exists and the row was
--         created before this migration (heuristic: row's outline_section_id
--         was used in a generation_output that has since been deleted).
--         In practice, since pre-fix rows have NULL generation_output_id and
--         the new trigger doesn't help retroactively, we delete all rows with
--         NULL generation_output_id where the source output has been deleted.
--         The trigger's "only delete if this is the source" logic is then
--         effective for post-fix rows.
--
-- Desired invariant: Project State may only contain memory derived from
-- generation outputs that still exist and are considered active/accepted.
-- ============================================================================

-- Step 1: Add the column (nullable for back-compat).
alter table public.section_embeddings
  add column if not exists generation_output_id uuid
  null;

-- Step 2: Index for the Delete Everywhere cascade check.
create index if not exists idx_section_embeddings_generation_output_id
  on public.section_embeddings (generation_output_id);

-- Step 3: Trigger that removes the source section_embeddings row when a
-- generation_output is deleted. Only fires if the section_embeddings row's
-- generation_output_id matches the deleted output (the "do NOT delete if
-- replaced by a newer output" case is handled implicitly — newer outputs
-- have different generation_output_id).
create or replace function public.delete_source_section_embedding()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Only delete the section_embeddings row if it was generated by the
  -- output being deleted. If a newer output has since replaced it
  -- (generation_output_id is now a different value), leave it alone.
  delete from public.section_embeddings
  where generation_output_id = old.id;
  return old;
end;
$$;

drop trigger if exists generation_outputs_delete_source_memory on public.generation_outputs;
create trigger generation_outputs_delete_source_memory
  after delete on public.generation_outputs
  for each row
  execute function public.delete_source_section_embedding();

-- Step 3b: Add FK constraints with ON DELETE CASCADE so the inverse
-- direction also works (delete section → cascade to outputs + memory).
-- section_embeddings: row keyed by outline_section_id (UNIQUE).
-- When the section is deleted, drop the section_embeddings row.
alter table public.section_embeddings
  drop constraint if exists section_embeddings_outline_section_id_fkey;
alter table public.section_embeddings
  add constraint section_embeddings_outline_section_id_fkey
  foreign key (outline_section_id)
  references public.outline_sections(id)
  on delete cascade
  not valid;
-- `not valid` skips the full-table scan (existing rows already pass since
-- outline_section_id is not null). The constraint is enforced for new rows
-- + cascade.

-- generation_outputs: row references outline_section_id (nullable).
-- When the section is deleted, drop the generation_outputs row.
-- (The output is tied to the section; deleting the section orphans it.)
alter table public.generation_outputs
  drop constraint if exists generation_outputs_outline_section_id_fkey;
alter table public.generation_outputs
  add constraint generation_outputs_outline_section_id_fkey
  foreign key (outline_section_id)
  references public.outline_sections(id)
  on delete cascade
  not valid;

-- Step 4: One-time cleanup of pre-existing dirty rows.
-- For rows with NULL generation_output_id, the source output was either:
--   a) Deleted before this migration left no lineage → memory is orphaned.
--      Action: delete the section_embeddings row.
--   b) Never had lineage (shouldn't happen with run-outline, but be safe) →
--      Leave alone (no way to know if the source is still valid).
-- Since (a) is the dangerous case and (b) shouldn't exist in normal flow,
-- we delete all NULL generation_output_id rows. This is a one-time cleanup
-- that re-establishes the invariant. Post-fix rows will have
-- generation_output_id populated, so this WHERE clause won't match them.
delete from public.section_embeddings
where generation_output_id is null;
